package day7

import org.junit.jupiter.api.Test
import kotlin.test.assertEquals

class TachylonManifoldAcceptanceTest {

    @Test
    fun `Counts beam splits`() {
        val puzzleInput = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent()

        assertEquals(21, countSplits(puzzleInput))
    }
}