package day7

import org.junit.jupiter.api.Test

class TachylonManifoldAcceptanceTest {

    @Test
    fun `Counts beam splits`() {
        val puzzleInput = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
        """.trimIndent()

        countSplits(puzzleInput)
    }
}